### ISSUE TITLE
admintools/tools/PointToRepairPERM.sqf

### ISSUE THREAD

**Issue by f3cuk** [noxsicarius/Epoch-Admin-Tools#138]
This does not permanently repair vehicles. After restart they revert to their old state. Dont know how to fix it.

**Comment by slayterson** [comment]
I've never had repair PERM ever work since 1.0.4.2, but idk. I'm about ready to take the repair script from service point and modify it to work in the admin menu lol.

**Comment by noxsicarius** [comment]
Did you ever update it? This has been working for almost a year now. I've recently used it to repair a completely blown up vehicle.

**Comment by slayterson** [comment]
Ya i updated to he last version, and have been checking back often. I will
check into it again tho.

**Comment by noxsicarius** [comment]
Let me know what you find. It might be a conflict with something. I've used it a number of times now to test my new AI spawner and safe zone system with no problems.
