### ISSUE TITLE
Update admin build

### ISSUE THREAD

**Issue by noxsicarius** [noxsicarius/Epoch-Admin-Tools#154]
Update rotation
Update distance for items
Add GUI system instead of using scroll menu

**Comment by bualdoot** [comment]
Any update on snapping being added? Snapping would fix the issue of having the bigger buildings spawn to close to you and rubber banding you into the sky. Could simply hit "F" to drop the item and the move farther away and pick it back up. Kill two birds with one stone and get snapping working :)

I am not the best at scripting, and I don't understand what the issue is. Why is it so difficult to add like snap build pro to the item placement? Don't have permission to use it or what? (hope that didnt come across rude, not meant that way.) I have been searching google for weeks trying to find some one that has successfully swapped in snap pro to admin tools, and while everyone seems to want it, haven't found someone that has. There is some one with a more basic Admin Tools that has snapping in it. So, its gotta be possible to add it to yours. What's it gonna take?

**Comment by noxsicarius** [comment]
This will be in the next update. It was originally delayed because it required you to modify files outside of the admin tools.

**Comment by bualdoot** [comment]
Ahh. Well, that sounds great. I've been comparing the snappro and adminbuild files for a few weeks, but can't figure out myself how I would go about doing it without breaking everything :)

**Comment by noxsicarius** [comment]
It requires a lot of modification. You have to pull out any reference to time and object requirement and then allow for replacement of last item.

**Comment by noxsicarius** [comment]
Figured out the permanent buildings (like houses and such) and have constructed a GUI for the building spawns. Still needs some cleanup and more stuff added to it though.

**Comment by noxsicarius** [comment]
Over one thousand spawnable items have been added to the GUI and there is an option for permanent or temporary spawns. It is now in testing and worthless items are being removed as they are found.

**Comment by bualdoot** [comment]
That is awesome! Can't wait to give it a try. Are these changes live in the TestBranch, or not downloadable yet?

**Comment by noxsicarius** [comment]
The GUI is not in the test branch yet. There are a lot of updates in it as well as performance enhancements. Most crates nos spawn instantly too.

**Comment by bualdoot** [comment]
Ah that is great. I've never had crates not spawn instantly though. So what do you mean by that? Do you mean they finish being filled instantly? When I chose the crate, as far as I can remember, it shows on the ground in front of me. But, when viewing the gear of the All Items/Weapons crate, it often times is still being filled with items, as I can see the scroll bar continuing to grow.

The crate timer dialogue doesn't seem to appear until after the crate has been filled though. So, in the case of the bigger crates, sometimes that takes a while.

Side note, Admin Menu disappears when using skin changer to full ghillie suit. (testbrach). I'll post a new issue for it, if I don't see that someone else has already. I don't recall it disappearing from master branch.

**Comment by noxsicarius** [comment]
Yes, they should be nearly instantly filled now. The lost admin menu has been fixed already. I found out about it yesterday. I did a security/efficiency upgrade that seemed to have caused an issue with skin changing so I removed it for that file.

**Comment by bualdoot** [comment]
Cool. Is that update in the testbranch yet then? Or what can I change to fix it? If I have to wait I can, I don't have to change my skin too terribly often :) Thanks for all your speedy, hard work.

**Comment by noxsicarius** [comment]
It is in the test branch

**Comment by noxsicarius** [comment]
If you are using the test branch, please send me updates about any bugs you find. Some of my commits were large updates that have a possibility for bugs.

**Comment by noxsicarius** [comment]
The gui is up and running. The only issue with the build system right now is the permanent spawn is not working. I have been trying to figure out why, but so far I have had no luck. This is the main thing holding up the release of 1.9.2

**Comment by noxsicarius** [comment]
Gui is now working with spawning permanent buildings

**Comment by noxsicarius** [comment]
Currently refining the offset of items

**Comment by bualdoot** [comment]
Sweet.updating to newest test and I'll let ya know if I find bugs.

**Comment by noxsicarius** [comment]
I plan on adding the ability to save towns using the base manager and import them just like the base system works right now. Will allow for people to build towns and post them for others to see and use without any problems.

**Comment by noxsicarius** [comment]
GUI and distance updates done. May need to work on the rotation more later on.
GUI: 
* commit 75da76abfd46ef13d35ffaf0d0a91d56a48e894a
* commit 2bfcd4f7e0da312b01e2fc302d47f18f64968230
* commit 6a265eca6123a58bbcbd6bfb0233f787fb4632c0
* commit dae1d90fb54c7703aeb1f8d18f9455c7a6fe46a6

Distance updates:
* commit f9dd281aa04c751198eef176d7ece97c28a791e8
