### ISSUE TITLE
Repair Player Crashed Vehicles

### ISSUE THREAD

**Issue by ATRealMaster** [noxsicarius/Epoch-Admin-Tools#200]
Me and Many Players always crash our vehicles and wreck them(blowing up), mostly helicopter, and I would really like a way to repair them or fix them, it is really frustrating if there is a lot of stuff inside.

**Comment by noxsicarius** [comment]
This is something that is already possible as I can almost always repair a destroyed car by repairing it a number of times very quickly, but it seems that very few people know about this trick. Almost like it is some kind of easter egg. I think I will add an option to restore destroyed vehicles that auto heals a number of times for this reason.
