### ISSUE TITLE
Logics of EAT_toClient

### ISSUE THREAD

**Issue by f3cuk** [noxsicarius/Epoch-Admin-Tools#201]
Think there is something wrong with the logics for most of the ``EAT_toClient`` stuff, they repeat themselves loads of times.

For instance, whenever somebody asks for admin help through the action menu. It pops up the "*** A Player needs help***" message loads of times. Or when a "normal" admin uses the tools, it popups the message saying the have activated X at least a few times.

**Comment by noxsicarius** [comment]
Nothing has been reported on this so far so I will now close it.
