### ISSUE TITLE
Admin tools forcing server time

### ISSUE THREAD

**Issue by herculys** [noxsicarius/Epoch-Admin-Tools#207]
tried multiple times reinstall server from the zero (epoch vanilla 1.0.5.1), and after install Epoch-Admin-Tools
still it is forcing my server to day time (ignoring [Time] in HiveExt.ini)

 (i want my server night)

**Comment by noxsicarius** [comment]
Weather/time has been disabled for now in the test branch and extends to v 1.9.3
It will be added back in for v2.0
The main reason for this is that there is mixed information coming in about it working great or screwing with the server. If it causes major issues for some then it is not worth the risk in a release.
