### ISSUE TITLE
Base Manager save to sqf and allowedObjects

### ISSUE THREAD

**Issue by bualdoot** [noxsicarius/Epoch-Admin-Tools#208]
I placed a bunch of buildings, walls, and other various objects using Admin Build. Then, used Base Manager to save the objects to SQF. It only saved the walls to the file. So, I started looking at the code and found that Export to SQF does a check of the objects against the DZE_allowedObjects string, and only exports objects that are in that list. So, My plan of using Admin build to create my custom mission areas, and then export to SQF, make various needed modifications, and then add the new file to the mission systems list of missions that can be spawned, won't work if I don't copy every object classname  from your many many object menu's, and add them to allowedObjects.

Now, I did exactly that, and its a nice long list, but, at least it copies everything to SQF that can be placed from the Admin Build. But, I don't know if having them in the allowObjects list is a bad idea for any sort of hacking or what not, so I created a new BaseManagement_allowedObjects list and changed the three (I believe) references to point to the new one.

My issue of course is that if you make any modifications or additions to your menu's, as you have mentioned you will, I will once again have to go through and copy all of them out again. So, does it really need to check a list or is there an easier way of compiling a list of the objects?

**Comment by noxsicarius** [comment]
Well you could save everything in the area. It is meant to save player built bases really, but this makes a valid point. I may add a new option to save all to sqf.

**Comment by bualdoot** [comment]
Maybe have two options to select from for saving. One that functions as is currently, and the other would include admin build items. If it just checks for all objects that would work too, but not sure if people would want it to copy trees, and everything else too. I may end up just using the 3D editor to build my missions from, since I have come to realize I will have to edit every line to format them the proper way if I use the save option. But, for building bases, could still be nice to save all if you had built around scenery items that you want included.

**Comment by noxsicarius** [comment]
The build system is still only 1/4 done. It has a long way to go still. The base save system is still unfinished as well. It will have more features and one thing I really want to do if possible is to save each base to its own sqf file. So you can have base1.sqf base2.sqf and the game can read both of them. This will remove the need to copy things over to the base manager file all the time. It will just require a lot of testing and some dll modifications.

**Comment by noxsicarius** [comment]
The base manager should now allow exporting arma buildings that have been placed. I have not checked to see if there will be a problem with it attempting to save pre-placed map objects or not yet.
