### ISSUE TITLE
Skin Changer makes Admin Menu disappear

### ISSUE THREAD

**Issue by bualdoot** [noxsicarius/Epoch-Admin-Tools#210]
Admin Menu disappears when using skin changer to full ghillie suit. (testbranch). I don't recall it disappearing from master branch.

When I chose to change skin to full ghillie suit, the Admin Menu no longer appears in scroll menu, and the only way to get it back is to relog. I've tried F10 and tried pressing F11 then F10, hoping to tell it to hide and then reappear. But, doesn't ever work. I can get this issue on multiple computers. I'm not seeing any errors in client or server RPT.

EDIT: Just noticed after changing skins, I do get a no character ID. So maybe I'm not being seen as me once I change skins.

**Comment by noxsicarius** [comment]
This has already been fixed as of commit 47119a3d6e2af51d144f93d99a8cf7662c3f53d0
