### ISSUE TITLE
Global Messaging

### ISSUE THREAD

**Issue by noxsicarius** [noxsicarius/Epoch-Admin-Tools#211]
I am considering adding a way to send a message to the entire server. All you do is scroll to the option and it brings up a text box. You can then type a message to the entire server. I could also make it a chat command where you type /globalMessage "message here". I could even add a way to choose how long to display it (in seconds)

What do you guys think about this? I know BEC has stuff like this, but I think it could be easy for any admin to have the option to send a TitleText message instead of a chat message that will disappear in half a second.

**Comment by bualdoot** [comment]
If it showed up as an Admin message, and not with the logged in name, that would be a nice feature. But, if it uses the character name, then how would it be different from using side chat?

**Comment by noxsicarius** [comment]
It will say either SERVER: (message) or ADMIN: (message)
The main thing I am trying to decide on is if it should be a title text (shows on the screen itself) or a chat message (shows in the chat box, most likely in red) If it is a title text everyone will surely see it, but if it is a chat message a spammer or lots of talk will make it disappear quickly. I think I am settling on making it a title text at the very top of the screen. This way it is not obstructing, but everyone will see it. I was actually logging on right now to start coding this.

**Comment by noxsicarius** [comment]
The tool is now live. The option appears near the bottom of the Admin Menu (Not enabled for Mod's). The tool opens a text box dialog where an admin can enter whatever text they wish. When the "Send" button is pressed the message will appear at the top of every client's screen in large red text "ADMIN: (message)".
