### ISSUE TITLE
weapon crate, only ammo (test branch)

### ISSUE THREAD

**Issue by bualdoot** [noxsicarius/Epoch-Admin-Tools#258]
Spawning the weapons crate, spawns a crate full of ammo, but no weapons. Used to work just fine, but in one of the last updates, something seems to of changed. Where is it pulling the item list from? Could I of edited a server file some where, or maybe it was the crate update from December maybe? All Weapons/Items crate seems to work just fine, has pretty much everything in it (almost everything).

I'm kinda noob when it comes to tracing the calls in the script to cfgweapons and what not. Never can find those files. Some crates have specified loot in places, while others don't. So, not sure how to figure out where to look.

**Comment by noxsicarius** [comment]
I have been moving crate items into the config file. I will be moving them to the variables file soon though. I realized that it is best to have the most modifiable items in config and the less modifiable ones in variables.

There was a spelling error in the config. Replace the crates section of your config and it will work again.
