### ISSUE TITLE
Contact Admin - Test Branch

### ISSUE THREAD

**Issue by bualdoot** [noxsicarius/Epoch-Admin-Tools#261]
This feature was working fine with the first version of it. But, something has been broken with it since then. Players say they have submitted a ticket, but my admin menu doesn't show anyone in the queue. I haven't seen any errors in the RPT, but I'll keep checking. Its been like this for a at least 2-3 weeks, maybe more.

**Comment by noxsicarius** [comment]
I will look into this. This is something I really want working well as it is something that is super useful for active admins.
