### ISSUE TITLE
BattlEye filters doesn't work

### ISSUE THREAD

**Issue by ThePjpollie** [noxsicarius/Epoch-Admin-Tools#266]
Hello there!

I've seen all your scripts and they are awsome! or at least the preview ;)
But I want to install this Admin tool, but I get "You were kicked off the game (BatllEye: PublicVariable Restriction #0"

I've re-installed the whole script... I've re-downloaded and uploaded the BattlEye files...
I even changed in the file 5 to 1 (front of the whole command)
I know thats dangerous but just wanted to try ;)

And nothing worked, still getting kicked... Anybody that can help me?

Kind Regards
PS Sorry for my English, it isn't my native language!

**Comment by noxsicarius** [comment]
Are you hosting your own server? Do you have infistar?

**Comment by ThePjpollie** [comment]
Im not owning my own server :)
Its being owned by nitrado.net

How can I see if i have infistar? Cant look now but if i found it will answer asap!


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Ricky Sanders <notifications@github.com> </div><div>Datum:2015-05-07  10:40  (GMT+01:00) </div><div>Aan: noxsicarius/Epoch-Admin-Tools <Epoch-Admin-Tools@noreply.github.com> </div><div>Cc: ThePjpollie <pieterjan.pollie@hotmail.com> </div><div>Onderwerp: Re: [Epoch-Admin-Tools] BattlEye filters doesn't work (#266) </div><div>
</div>Are you hosting your own server? Do you have infistar?

**Comment by ThePjpollie** [comment]
I don't think I have infistar :)

**Comment by noxsicarius** [comment]
I don't know how they operate so I don't know what is causing this. It seems like you may have put the filters in the wrong spot or they overwrite the filters every time. You could try posting to the forum.

**Comment by ThePjpollie** [comment]
I have like a cfgDayz folder with in that BattlEye and all the txt files, but all videos i see... they just drop it in BattlEye folder in tje root folder, i have that, tried that but the only thing in there is unstall :(


Verzonden vanaf Samsung Mobile.<div>-------- Oorspronkelijk bericht --------</div><div>Van: Ricky Sanders <notifications@github.com> </div><div>Datum:2015-05-09  00:41  (GMT+01:00) </div><div>Aan: noxsicarius/Epoch-Admin-Tools <Epoch-Admin-Tools@noreply.github.com> </div><div>Cc: ThePjpollie <pieterjan.pollie@hotmail.com> </div><div>Onderwerp: Re: [Epoch-Admin-Tools] BattlEye filters doesn't work (#266) </div><div>
</div>
I don't know how they operate so I don't know what is causing this. It seems like you may have put the filters in the wrong spot or they overwrite the filters every time. You could try posting to the forum.

---

**Comment by noxsicarius** [comment]
Well if modifying the files did nothing, that means the only possible explanation is that they are using different files elsewhere or they replace the files on restart.
