### ISSUE TITLE
Add support for single currency

### ISSUE THREAD

**Issue by noxsicarius** [noxsicarius/Epoch-Admin-Tools#273]
Have an option to enable admin control of single currency in the config files for those who have it or make it auto detect the single currency install like the admin building does with snap pro.

Possible options:
* view currency
* add currency (might require cap depending on the single currency mod)
* remove currency (remember to protect from negative values)
* set currency to 0 (fast way to remove all money)

**Comment by slayterson** [comment]
I have another authers currency script worked into your admin tools, modified a bit to remove errors, if you want it. i can put up a pull.

**Comment by noxsicarius** [comment]
Too many options. Best to use the community made addons.
