### ISSUE TITLE
the menu is poping up ingame

### ISSUE THREAD

**Issue by Trevsaster14** [noxsicarius/Epoch-Admin-Tools#274]
the scroll menu is not poping up i followed the tut and i did everything correct. could infistar be causing the issue?

**Comment by tinboye** [comment]
do you get any error regarding dialog.hpp, did u make sure that you added your steam 64 ID to the admin list?

**Comment by Trevsaster14** [comment]
no error's and im using the correct id's

**Comment by tinboye** [comment]
add me on steam, and  i will see if i can help you get to the bottom of this.  username is tinboye

**Comment by noxsicarius** [comment]
Check your error files. Post the config.sqf and init.sqf so we can have a look at it. It is most likely an issue in the config.
