### ISSUE TITLE
Menu not popping up, cant rejoin can move but epoch screen only

### ISSUE THREAD

**Issue by Okamigado** [noxsicarius/Epoch-Admin-Tools#278]
Here is the paste bin: 
http://pastebin.com/jAqryE7A

**Comment by noxsicarius** [comment]
I will need the client rpt. It is found in the local appdata

**Comment by Okamigado** [comment]
http://pastebin.com/rdW8FWwK

**Comment by Okamigado** [comment]
After repeatedly trying i can join by luck, but no menu sadly.

**Comment by noxsicarius** [comment]
Try to reinstall. The tools don't seem to be called at all.

**Comment by Okamigado** [comment]
I have tried multiple times

**Comment by noxsicarius** [comment]
Show me the init and config. The issue is that it is not loading any section of the tool. It should at the very least load the variables and config, but there is no indication that is happening. From looking at the logs it just seems like it isn't installed at all.

**Comment by Okamigado** [comment]
Init:
http://pastebin.com/bCVLb7W9

Config:
http://pastebin.com/rutTTrU6

**Comment by noxsicarius** [comment]
The id in the config doesn't seem to match the one you are loading into the game with

**Comment by Okamigado** [comment]
Where can i find this specific id then?

**Comment by Okamigado** [comment]
I think i have found the id you mean, im giving it a try.

**Comment by Okamigado** [comment]
Looking at the console at the moment i seem to be joining the game with my steam id that was in my config.

**Comment by noxsicarius** [comment]
Are you joining just fine now? If so send me the server rpt again. Maybe this time it will show that the tool is loading to some extent

**Comment by Okamigado** [comment]
Ok hold on, still having the problem where i cant join properly and that i have to constantly try i will send you it once i actually get in again

**Comment by noxsicarius** [comment]
I did see an issue with the server files in the rpt. It seemed to come from the server files and not the mod.

**Comment by Okamigado** [comment]
That issue only started with the admin tools install when i took it a way again i was able to rejoin and such just fine.

**Comment by Okamigado** [comment]
Is there anyway we can use teamviewer or such to do a fresh install?

**Comment by Okamigado** [comment]
http://pastebin.com/7sjZLpb4

**Comment by Okamigado** [comment]
I got the menu working, i installed on the chernarous 17 folder instead and it worked
