### ISSUE TITLE
Spectate Camera Switcher

### ISSUE THREAD

**Issue by OlofTheBald** [noxsicarius/Epoch-Admin-Tools#279]
The switchCamera keyword supports multiple camera views but Admin Tools only supports the external view. There are cases where it would be useful to see the 1st person (INTERNAL) view. Could you look into adding a menu that allows admins to switch camera view dynamically while spectating a player?

Thanks!

**Comment by noxsicarius** [comment]
Will have this in for next release

**Comment by dristy** [comment]
Thanks, much appreciated! I looked at doing it myself and decided I'd probably break something. I'm good with Java and Python, but kindergarten level with SQF.

Thanks again.

**Comment by noxsicarius** [comment]
sqf is basic and c++ mashed together. java is strictly for object oriented so that wouldn't help much with this.

**Comment by OlofTheBald** [comment]
Me and another admin from my group's server have started testing this, I've found that the keypad Enter key works just as it does on my own player character. In light of this, the menu might not be needed since third person and first person are really all the views admins need.

**Comment by noxsicarius** [comment]
Will probably add a message to explain this then.
