### ISSUE TITLE
Safe Zone upgrades

### ISSUE THREAD

**Issue by noxsicarius** [noxsicarius/Epoch-Admin-Tools#288]
The current system is a modified AGN safezone script with a vehicle safe zone system. This works fine, but is a bit limited. I plan to write my own original safezone script to make things as efficient as possible.

Plans for my own version:
- [x] Player god mode (including disabled unconsciousness)
- [x] Vehicle god mode
- [x] No shooting vehicle/player/grenade
- [x] Anti theft
- [x] Use can_build system to auto detect safe zones
- [x] Allow users to add custom locations
- [ ] Possible option for plot pole safe zones? @nidico100
- [x] Optional speed limit
- [x] Keep my custom additions to the AGN version such as zombie shield, but make it optional
- [X] Optional AI shield

**Comment by noxsicarius** [comment]
The new system will be a mashup of a number of good scripts (will be listed in the file for credits). It will be faster and more efficient to do this rather than start from the ground up. This will let me make the best possible script without any complications and allow for the most customization by users.

**Comment by Evocation** [comment]
+1 (y)

**Comment by nidico100** [comment]
I think it will be an awesome script when it's finished. 
If you need a tester just say it.

**Comment by noxsicarius** [comment]
I will let you guys know so you can test for me. Worked on it for most of the day. It is half done and works great so far.

**Comment by nidico100** [comment]
Nice to hear :)

**Comment by noxsicarius** [comment]
Anyone know how to wipe an AI killed handler? I ran the standard remove and remove all with a delay to let the handle finish, but it still doesn't seem to wipe. Delete works, just leaves a handler lost error behind.

**Comment by noxsicarius** [comment]
How would you like anti-theft handled? Should it be done by not allowing gear access while pointing at a player, or not allowing while near a player?

**Comment by noxsicarius** [comment]
Alright guys, new safe zone system added in. I need it tested. It doesn't have plot pole safe zones yet. I only really need anti-theft tested for me. It should allow FRIENDS to access your gear, but no one else. If you attempt to access someones gear it auto-redirects to your own gear. No need to walk away like with infistar or look away like with AGN. Full auto process now. I hope.

**Comment by nidico100** [comment]
i could test

**Comment by nidico100** [comment]
where to get the newest testing branch? the thing on dropbox is version 1.10.4

**Comment by noxsicarius** [comment]
All branches can be downloaded right on here. The dropbox is only for places that block github (some schools do it for "cheating" problems) https://github.com/noxsicarius/Epoch-Admin-Tools/archive/TestBranch.zip

**Comment by nidico100** [comment]
okay thx

**Comment by noxsicarius** [comment]
If you tested it already, please redownload and replace your Activate.sqf
I did a bugfix that didn't push properly. The zones won't work without that fix.

**Comment by nidico100** [comment]
okay i will use the bugfix today, yesterday i couldn't test, i was scripting a mission for my server

**Comment by noxsicarius** [comment]
Also test the teleport to me if possible. After the variable handle changes it had some issues that I hope I corrected.

**Comment by nidico100** [comment]
I am starting the server right now.
I will test specially:
- Safezones
- Teleport
anything else?

**Comment by noxsicarius** [comment]
I think teleporting others while they are in vehicles still needs testing. Just have someone get in as the driver and teleport them to you. This only worked while outside vehicles previously.

**Comment by nidico100** [comment]
Now the action menu is working, before it wasn't working for me.
but the server rules looks buggy only the first has an dot the others don't
but i will have a look about the config, because i can't see the admin menu

**Comment by nidico100** [comment]
i added my uid to the config as last time, but i'm not an admin

**Comment by noxsicarius** [comment]
Yes, that has always been like that. I never got around to fixing it. If you know how let me know. There were changes to the config file so you will need to replace it. If you think everything is good, try pressing F1 to teleport. It will work without the menu so long as the id is correct and there are no errors. If you are sure the ID is right and it still doesn't work, then check arma2oaserver.rpt and arma2oa.rpt for errors

**Comment by nidico100** [comment]
i replaced the whole admintools folder and added my id to the config

**Comment by nidico100** [comment]
i found in the rpt:
15:26:50 "ERROR: Cannot Sync Character Nidico as no characterID"

**Comment by nidico100** [comment]
i try a restart

**Comment by nidico100** [comment]
Teleportation works fine for me :)
After restart i also can see the admin menu now

**Comment by nidico100** [comment]
there's no config variable for the transformation menu, so how can i disable it?

**Comment by noxsicarius** [comment]
transform is only given to admins, not players. The teleport works for YOU or when you tp to me?

**Comment by nidico100** [comment]
ah okay
when i press f1 and teleport to any location it works
i'm alone on the server at the moment, because the others are working

**Comment by noxsicarius** [comment]
Alright, go to the server browser and filter for Nox's. Join that for me real fast. I can test teleport there.

**Comment by nidico100** [comment]
can't find wait i will look in dayz launcher

**Comment by nidico100** [comment]
nope you're not on the list :/

**Comment by noxsicarius** [comment]
Check the arma 2 server browser again. You may have to wait a minute for filter to finish

**Comment by nidico100** [comment]
i think i know the problem i am using beta 112555 not the new steam update

**Comment by noxsicarius** [comment]
Oh wow. I joined multiplayer using LAN and it blocked the server from internet. Weird.

**Comment by nidico100** [comment]
arma 2 is weird :D

**Comment by noxsicarius** [comment]
Wait why are you using such an old build?

**Comment by nidico100** [comment]
i made an server some months ago and it worked with this version so i still use it :) never change a running system

**Comment by noxsicarius** [comment]
Can you still play on other servers with that version of the game? Thought you had to have the 125548 update for the steam id change to work.

**Comment by nidico100** [comment]
yes it's possible with using remote in server browser
i am updating now to 125548 (75mb left)

**Comment by noxsicarius** [comment]
You can update the server pretty easily, just recopy your game files to the server folder. You may  not need to add the steamID thing to the config and that's about it.

**Comment by nidico100** [comment]
yeah but i will have to change every single characterid in the database to the new steam id

**Comment by nidico100** [comment]
okay it's updated now

**Comment by noxsicarius** [comment]
Make sure to change the ping requirement too. Not sure what my ping will be.

**Comment by noxsicarius** [comment]
Do you still get new players on the server?

**Comment by nidico100** [comment]
im on the server now
and it's an friends only server at the moment, because i'm too lazy to add battleeye filters

**Comment by nidico100** [comment]
my game crashed while on the ammo box

**Comment by nidico100** [comment]
can't find the server anymore

**Comment by noxsicarius** [comment]
No big deal. testing is relatively done for now. I found the error with anti-theft though. I used isNil for an object. Server may have DC due to TWC being a terrible company. Couldn't game all day yesterday.

**Comment by nidico100** [comment]
okay :) good luck with fixing the bugs

**Comment by noxsicarius** [comment]
Already fixed a few :P

**Comment by nidico100** [comment]
nice :D

**Comment by noxsicarius** [comment]
Any suggestions for the flying thing you talked about?

**Comment by nidico100** [comment]
i don't use it so it doesn't matter i just find it's very difficult to control

**Comment by noxsicarius** [comment]
You know you can hover by pressing space right? It's easier with fast walk on though. You can just hover and move tp forward now. Before you couldn't hover and move (because hover works by resetting coordinates to basically teleport you constantly to the same height as you fall).

**Comment by nidico100** [comment]
nope i didn't know but thanks for the info :)

**Comment by noxsicarius** [comment]
That's a problem then. Guess I didn't add a screen message for it or something. Maybe I should add a server rules kind of thing for tool instructions.

**Comment by nidico100** [comment]
that's a good idea

**Comment by noxsicarius** [comment]
Safe zone system is working and stable.

**Comment by nidico100** [comment]
okay nice

**Comment by nidico100** [comment]
i will test it later

**Comment by nidico100** [comment]
Teleport Player to me doesn't work

**Comment by nidico100** [comment]
and when i'm in a safezone i can shoot zombies

**Comment by nidico100** [comment]
I generally can shoot

**Comment by noxsicarius** [comment]
Admins are not affected by some safe zone restrictions like shooting and anti theft. Shooting can disrupt their view and they may need to interact with dead players.

**Comment by noxsicarius** [comment]
I was relatively sure I fixed the teleport issue. Find the Sleep 1.5; in the tptome file and change it to 3. Let me know if that works.

**Comment by nidico100** [comment]
i don't have battleeye, infistar or any other antihack installed

**Comment by noxsicarius** [comment]
No, you do have one, which is the admin tools one. If you were to remove the antihack line from the init, this would work fine. I had a bypass that worked perfect, but it took longer to execute than the new code (lots more efficient), which I think made it so the server didn't have time to distribute the variables to every client so the server knew who was allowed to be moved and not get bounced by the antihack.

**Comment by nidico100** [comment]
oh okay

**Comment by noxsicarius** [comment]
If you have a server up and need to test the teleport I can come in

**Comment by nidico100** [comment]
i only have the 112555 server private hosted

**Comment by noxsicarius** [comment]
i might be able to get in with a newer version of the game. not sure

**Comment by nidico100** [comment]
you have to join via remote with the ip
pw: 1234
ip: 91.42.88.105
say okay when you noticed the ip so i can delete my comment

**Comment by nidico100** [comment]
it's possible to have both arma 2 oa version at the same time on steam (1st the normal arma2oa on upt to date / 2nd arma2oa and under properties -> betas -> 112555 selected then start with the version you want)

**Comment by noxsicarius** [comment]
you can remove it

**Comment by noxsicarius** [comment]
keep getting timeout on auth. Did notice you have a variable error in your debug though

**Comment by nidico100** [comment]
what error?

**Comment by nidico100** [comment]
i stopped the server so don't worry if you can't join anymore

**Comment by noxsicarius** [comment]
Oh i Know why. My id is a steam id, your game doesn't know what to do. Forgot the id change screwed with the old version. Look at your arma2oa rpt. Has all the errors.

**Comment by nidico100** [comment]
http://pastebin.com/nkpQXcM1

**Comment by nidico100** [comment]
the steam id is just a longer uid in my data base, so why it's creating errors? it's just a longer number or is it more?

**Comment by nidico100** [comment]
Did you ever try the speed boost on a bike? :D it's funny
http://i.imgur.com/CLSyP3o.jpg
look at that speed :D

**Comment by noxsicarius** [comment]
Dude I love using it on the bike. That' why it is on the temporary vehicle spawn list. Use the bike and fast walk over the ocean. The older arma version doesn't know how to handle an id string longer than the default. It's not seen as a valid entry.

**Comment by nidico100** [comment]
it's really funny :D 
yeah okay that make sense

**Comment by nidico100** [comment]
protected zone on aircraft dealer is buggy

**Comment by noxsicarius** [comment]
I need more info on what is going on.

**Comment by nidico100** [comment]
the message which is shown there say godmode disabled when you are in there

**Comment by noxsicarius** [comment]
I found the issue, but it is WAY worse than that if you disable auto detect zones. It spams the screen with entered/exited zone every .2 seconds. Can be fixed by removing  && !inZone on line 184 of the safe zone file

**Comment by nidico100** [comment]
okay

**Comment by noxsicarius** [comment]
You manage to test the teleport with the higher sleep time yet?

**Comment by nidico100** [comment]
nope sorry school started again and maybe tonight or tomorrow

**Comment by noxsicarius** [comment]
No big deal. Just doing some updates to increase efficiency for the scripts that I don't want to push until I know the current state of the system.

**Comment by nidico100** [comment]
I can't test it today sorry. My phone is dead and I need the data very fast and my focus is now on that and school. Maybe on the weekend.

**Comment by noxsicarius** [comment]
If you don't mind a non-power user phone you could grab an LG power for $20 on sale at Walmart. Has a quad core and is easily worth $80.
Grab up the new variable file. I reverted the teleport to a working state. For whatever reason the server just isn't passing the variable to clients like it is supposed to. Must be one of those notorious arma glitches.

**Comment by nidico100** [comment]
I bought an OnePlus X now, because it's an android were you don't loose the warranty if you root it and it's cheap and very good. I wasn't much on the computer the last days. It was examine time, but today our school year ends with the grades.
