### ISSUE TITLE
Admin tool sometimes does not work

### ISSUE THREAD

**Issue by MasakrPetrov** [noxsicarius/Epoch-Admin-Tools#290]
Hi,
sometimes admin tool is not working. I see a notification is turned on, but does not god mode or anything else. It works only graphically vehicle list. This happened especially after my death or reboot the server. I turn off the game, start the game and start to work. I do not know what's wrong :-(

**Comment by noxsicarius** [comment]
Which branch and version are you using?

**Comment by MasakrPetrov** [comment]
You are using Epoch Admin Tools version 1.10.0
by NoxSicarius

**Comment by noxsicarius** [comment]
This is not a known issue with the tool and I don't see how it could be happening. There are a number of resets to the tool. Even entering a vehicle recalls the entire tool system, which should remove any errors. Do you see any errors in the report files?

**Comment by MasakrPetrov** [comment]
Ok. I write when I'm at home. Thx

**Comment by MasakrPetrov** [comment]
20:59:56 Server: Object 4:1331 not found (message 70)
21:00:09 "RUNNING EVENT: crash_spawner on [2016,1,28,10,0]"
21:00:09 "CRASHSPAWNER: 100% chance to start a crashing Ka-52 (černý) with loot table 'MilitarySpecial'"
21:00:09 "CRASHSPAWNER: Ka-52 (černý) started flying from [16240,10000] to [14458.6,5495.92] NOW!(TIME:3303||LT:MilitarySpecial)"
21:00:19 "DZAI Monitor :: Server Uptime: 0:58:13. Active AI Groups: 9."
21:00:19 "DZAI Monitor :: Static Spawns: 1. Respawn Queue: 1 groups queued."
21:00:19 Error in expression <rArray),(count DZAI_respawnQueue)];
if (_reportDynOrVehicles) then {diag_log for>
21:00:19   Error position: <_reportDynOrVehicles) then {diag_log for>
21:00:19   Error Použita nedefinovaná proměnná: _reportdynorvehicles
21:00:19 File z\addons\dayz_server\DZAI\scripts\DZAI_serverMonitor.sqf, line 195

**Comment by noxsicarius** [comment]
This is not an admin tool error, it's a dzai error in the dzai_servermonitor file.

**Comment by MasakrPetrov** [comment]
Where can I find an error file admin tools?

**Comment by noxsicarius** [comment]
That file has errors for every part of the game.

**Comment by MasakrPetrov** [comment]
Ok. So it means that the error is on the server side?

**Comment by noxsicarius** [comment]
Well a server monitor error may cause issues with it, but I can't be sure.

**Comment by MasakrPetrov** [comment]
Ok. Thx for answer.
