### ISSUE TITLE
Test Branch "Teleport to me"

### ISSUE THREAD

**Issue by 2000jago** [noxsicarius/Epoch-Admin-Tools#292]
Hi,
Using the "Teleport to Me" option does nothing. (Get the prompt to choose the username of the player to TP to me but when I select them, nothing happens at all.)

Teleport (myself) to location and Teleport (myself) to player works just fine.

Tried on freshly rebooted server without success. Same after relog.

**Comment by 2000jago** [comment]
This might be useful:

**Client RPT:**

tempList = tempList + _x;
EAT_PVEH_teleportFix = ["add",_UID>
  Error position: <+ _x;
EAT_PVEH_teleportFix = ["add",_UID>
  Error +: Type Object, expected Number,Array,String
File mpmissions\__CUR_MP.Chernarus\admintools\tools\Teleport\TPtoME.sqf, line 26
String STR_EVAL_TYPENAN not found
Error in expression <(getPlayerUID _x);

tempList = tempList + _x;
EAT_PVEH_teleportFix = ["add",_UID>
  Error position: <+ _x;
EAT_PVEH_teleportFix = ["add",_UID>
  Error +: Type Object, expected Number,Array,String
File mpmissions\__CUR_MP.Chernarus\admintools\tools\Teleport\TPtoME.sqf, line 26
String STR_EVAL_TYPENAN not found
Error in expression <(getPlayerUID _x);

tempList = tempList + _x;
EAT_PVEH_teleportFix = ["add",_UID>
  Error position: <+ _x;
EAT_PVEH_teleportFix = ["add",_UID>
  Error +: Type Object, expected Number,Array,String
File mpmissions\__CUR_MP.Chernarus\admintools\tools\Teleport\TPtoME.sqf, line 26

**Server .RPT:**  nothing

**Comment by noxsicarius** [comment]
I may have fixed the issue. I was adding an object to an array instead of the object ID

**Comment by 2000jago** [comment]
Nope, still nothing.  **Client RPT** says:

tempList = tempList + _UID;
EAT_PVEH_teleportFix = ["add",_U>
  Error position: <+ _UID;
EAT_PVEH_teleportFix = ["add",_U>
  Error Generic error in expression
File mpmissions\__CUR_MP.Chernarus\admintools\tools\Teleport\TPtoME.sqf, line 26

**Comment by noxsicarius** [comment]
generic error. That's pretty helpful... There doesn't seem to be any reason for it so I will have to look some more.

**Comment by 2000jago** [comment]
Thanks.  Will be ready to test.  ;)

**Comment by noxsicarius** [comment]
Try deleting line 43 and 26 for me. They don't serve much purpose for the one calling the function. It's mostly important for the one being teleported to have the templist setup to bypass the antihack for a few seconds. It seems to be the issue here and there isn't a reason it should be.

**Comment by 2000jago** [comment]
Ok, I removed 43 and 26 and yes indeed it works now.  However, it takes a few seconds to happen. I get the message "Teleporting USERNAME" on screen for about 3 seconds then the teleported user appears.  Server and Client RPT don't seem to be complaining.

**Comment by noxsicarius** [comment]
So it is working fine now? There is a built in delay at the moment to rule out the possible issue of the client not getting the bypass variable before it is teleported resulting in an antihack issue.

**Comment by noxsicarius** [comment]
I also think I figured out why the generic error was occurring. This language doesn't have a proper push command so I have had to use the more crude way of appending array elements and I may have done the append incorrectly for this language. (It is hard to keep languages separate when you have worked with as many as I have)

**Comment by 2000jago** [comment]
Well it working just fine now.  Thanks for applying your skills to this matter.  If you need anything else tested, feel free to ask.

**Comment by noxsicarius** [comment]
Check your server rpt for me and make sure it didn't get any error from that teleport. The possible append issue should be present in the event handlers on the server too. I will be doing testing to see if I was doing it right or not.

**Comment by 2000jago** [comment]
OK, multiple teleport tests later, NO complaints in server or client RPT.

**Comment by 2000jago** [comment]
This was strange:  I teleported myself to a different location.  Ran about 20m and teleported the user again.  He was not teleported to me but to the location I teleported myself 20m away...

**Comment by noxsicarius** [comment]
Seems to me the game didn't quite update your position yet. (The game takes an update from your client every so often) This shouldn't be a common issue. I will look into it, but I need you to do one test. Give the guy a car, and try the teleport with him in it. I added a way to teleport players in vehicles recently, but I never had a chance to test it.

**Comment by 2000jago** [comment]
OK, spawned a SUV, player got in, tried teleport him to me.  No go.  Tried another two times, nothing.
He gets out the SUV and can teleport to me, no problem.
Server RPT, nothing, client says:

WARNING: Function 'name' - 79e40080# 1058664: ghillie_top.p3d REMOTE has no unit
 - network id 2:3516
 - person Boris Vitek
 - dead
Error in expression < = alive _agent;
_targetPos = getPosATL _target;



_agent moveTo _targetPos;
_a>
  Error position: <_target;



_agent moveTo _targetPos;
_a>
  Error Undefined variable in expression: _target
WARNING: Function 'name' - 79e40080# 1058664: ghillie_top.p3d REMOTE has no unit
 - network id 2:3516
 - person Boris Vitek
 - dead
WARNING: Function 'name' - 79e40080# 1058664: ghillie_top.p3d REMOTE has no unit
 - network id 2:3516
 - person Boris Vitek
 - dead
WARNING: Function 'name' - 79e40080# 1058664: ghillie_top.p3d REMOTE has no unit
 - network id 2:3516
 - person Boris Vitek
 - dead

**Comment by 2000jago** [comment]
If I get in the vehicle (alone) I can teleport myself and the vehicle, no issues.
If the player gets in the vehicle with me I can STILL teleport the vehicle with the both of us in it, no issues.

**Comment by noxsicarius** [comment]
This will take more looking into. It's not necessary for the tools, but it is a requested function and I do see it's important uses. It seems there is some kind of issue with the game targeting the player skin rather than the player.

**Comment by 2000jago** [comment]
Well I have a good setup for testing, so just shout if you need.

**Comment by noxsicarius** [comment]
It would be great if you could test the return teleport player option I just added. It can be tested one of two ways: from the player ticket menu or the teleport menu. The option title is: Return Player to Last Pos. 

To test it: 
Replace all admintool files NOT INCLUDING the config.sqf (so you don't have to redo the options)
Teleport a player to you, then use the return option. 
It should send the player back to their exact position when you moved them to you. Might be easiest to put them in a trader city and try to teleport them into a field then back. Easiest way to be sure it sent back to the right place.
