### ISSUE TITLE
client rpt complaint

### ISSUE THREAD

**Issue by 2000jago** [noxsicarius/Epoch-Admin-Tools#293]
I just noticed the client rpt file is complaining about something:
----------------------------------------------------------
"Admin Tools: config.sqf loaded"
"Admin Tools: variables.sqf loaded"
Error in expression <";  

if ( !((getPlayerUID player) in AdminList) && !((getPlayerUID player) in>
  Error position: <AdminList) && !((getPlayerUID player) in>
  Error Undefined variable in expression: adminlist
File mpmissions\__CUR_MP.Chernarus\init.sqf, line 137
----------------------------------------------------------

Server rpt mentions no such issue and everything appears to be working just file.
Line 136 - 140 of my init.sqf is as follows:
--------------
		// Epoch Admin Tools
	if ( !((getPlayerUID player) in AdminList) && !((getPlayerUID player) in ModList)) then 
	{
	  [] execVM "admintools\antihack\antihack.sqf"; // Epoch Antihack with bypass
	};
--------------

**Comment by noxsicarius** [comment]
This is no longer part of the new tools. Keep the exec line, but remove the if around it. You can see an example in the readme.

**Comment by 2000jago** [comment]
Yep, that fixed it.  Thanks.
