### ISSUE TITLE
Error in expression

### ISSUE THREAD

**Issue by 2000jago** [noxsicarius/Epoch-Admin-Tools#295]
After fresh install of testbranch, server rpt says:
====================================================================
21:02:38 "Admin Tools: variables.sqf loaded"
21:02:38 Error in expression <ntools\variables.sqf"
EAT_adminList = EAT_adminList + EAT_superAdminList; 
EAT>
21:02:38   Error position: <EAT_adminList + EAT_superAdminList; 
EAT>
21:02:38   Error Undefined variable in expression: eat_adminlist
21:02:38 File mpmissions\DayZ_Epoch_17.Chernarus\admintools\variables.sqf, line 3
21:02:38 "Admin Tools: config.sqf loaded"

====================================================================

Line 1-5 of variables.sqf as follows:

// Do not modify this file unless you know what you are doing

EAT_adminList = EAT_adminList + EAT_superAdminList; // add SuperAdmin to Admin
EAT_adminModList = EAT_adminList + EAT_modList; // Add all admin/mod into one list for easy call
if ((getPlayerUID player) in EAT_adminModList) then {EAT_isAdmin = true;} else {EAT_isAdmin = false;}; // Discern if player is admin

**Comment by noxsicarius** [comment]
This could be causing an issue with the bypass too. Does your config have these variables:
	//Replace 111111111 with your ID. 
	EAT_superAdminList = [
	"111111111", // <player name>
	"999999999" // <player name>
	];
	EAT_adminList = [
	"999999999", // <player name>
	"999999999" // <player name>
	];

**Comment by 2000jago** [comment]
Yep. My config contains this:

	//Replace 111111111 with your ID. 
	EAT_superAdminList = [
	"76561198067303598", // <David>
	"999999999" // <player name>
	];
	EAT_adminList = [
	"999999999", // <player name>
	"999999999" // <player name>
	];
	EAT_modList = [
	"999999999", // <player name>
	"999999999" // <player name>
	];

**Comment by noxsicarius** [comment]
Does config come before variables in the init.sqf

**Comment by 2000jago** [comment]
Variables first, then config.

**Comment by noxsicarius** [comment]
Switch them. Config must be first. Config sets your presets, the variables set up everything.

**Comment by noxsicarius** [comment]
Paste the following 
	
	~~~~java
	call compile preprocessFileLineNumbers "admintools\config.sqf"; // Epoch admin Tools config file
	call compile preprocessFileLineNumbers "admintools\variables.sqf"; // Epoch admin Tools variables
	~~~~
	
	Directly under this:
	
	~~~~java
	call compile preprocessFileLineNumbers "server_traders.sqf";
	~~~~

**Comment by 2000jago** [comment]
Solved.

NO idea how that got changed around but no doubt I'm responsible.  Well spotted and thank you.

(I was hoping this may resolve the teleporting issue, but just tested and that issue persists.)
