### ISSUE TITLE
Remove Humanity From Self or Target

### ISSUE THREAD

**Issue by 2000jago** [noxsicarius/Epoch-Admin-Tools#297]
Instead of going to the choice of quantities, I get the following message immediately:

"Error: No player selected" 

If I ADD humanity to myself I get option to select how much to add.  I select 100 (for example) THEN I go to the "remove humanity from self or target, it goes to the quantity selection menu and works correctly if I try to decrement my humanity.

**Comment by noxsicarius** [comment]
Will check this out later. It's probably something to do with a loop exit clause.
