### ISSUE TITLE
init.sqf problems

### ISSUE THREAD

**Issue by Josh22799** [noxsicarius/Epoch-Admin-Tools#299]
I have followed all the instructions but keep getting this in my .rpt file no mater what I change in my init.sqf file.

```
\\AdminTools
[] execVM "admintools\Activ>
16:51:04   Error position: <\\AdminTools
[] execVM "admintools\Activ>
16:51:04   Error Invalid number in expression
16:51:04 File mpmissions\DayZ_Epoch_11.Chernarus\init.sqf, line 100
16:51:04 Error in expression <ns\DayZ_Epoch_11.Chernarus\init.sqf"
```

Line 100 is empty.

```
98 - //Start Dynamic Weather
99 - execVM "\z\addons\dayz_code\external\DynamicWeatherEffects.sqf";
100 - 
101 - #include "\z\addons\dayz_code\system\BIS_Effects\init.sqf";

```

init.sqf file is attached below. Any help would be appreciated. I have been trying to get this to work for two days...
[init.zip](https://github.com/noxsicarius/Epoch-Admin-Tools/files/232804/init.zip)

**Comment by noxsicarius** [comment]
line 100 has a semicolon. You need to remove it.
