### ISSUE TITLE
Scroll menu doesn't show up whenever I'm in game

### ISSUE THREAD

**Issue by iPopYouDrop** [noxsicarius/Epoch-Admin-Tools#301]
Title says it all, I've got my UID correct and idk what else to do pleas help!

**Comment by iPopYouDrop** [comment]
I even redid my server and admintools  today, still not showing up
NOTHING IS WORKING

**Comment by noxsicarius** [comment]
Post in the rpt file so I can see what's going on

**Comment by noxsicarius** [comment]
It looks like the infistar systems have changed and he may be disallowing all command menus. Depending on what the rpt files say you will have to enable command menus before it even attempts to let anything through again.

**Comment by iPopYouDrop** [comment]
Will do, putting it in paste bin rightnow!
Thanks for reply btw

**Comment by iPopYouDrop** [comment]
https://www.mediafire.com/?q13izhioi3qbtdi
I exceeded the limit on pastebin
not sure what you mean by server and client I could only find one RPT file

**Comment by iPopYouDrop** [comment]
Not sure how I would be able to do this but if you can get it working I
would greatly appreciate it!

**Comment by noxsicarius** [comment]
The most likely cause of this is
16:46:22   Error Missing ;
16:46:22 File z\addons\dayz_server\init\server_functions.sqf, line 804

**Comment by iPopYouDrop** [comment]
Alright, will post back if this works!

**Comment by iPopYouDrop** [comment]
What's missing the semi colon?
	if (!((isNil "_x") || {(isNull _x)})) then {
		// Epoch Admin Tools
        if(vehicle _x != _x && !(vehicle _x in PVDZE_serverObjectMonitor) && (isPlayer _x)  && !((typeOf vehicle _x) in DZE_safeVehicle) && (vehicle _x getVariable ["MalSar",0] !=1)) then {
			diag_log ("CLEANUP: KILLING A HACKER " + (name _x) + " " + str(_x) + " IN " + (typeOf vehicle _x));
			(vehicle _x) setDamage 1;
			_x setDamage 1;
			sleep 0.25;

**Comment by iPopYouDrop** [comment]
It's still not working :/

**Comment by iPopYouDrop** [comment]
I added some things here is another RPT
https://www.mediafire.com/?q13izhioi3qbtdi

**Comment by iPopYouDrop** [comment]
That RPT might still saying because I didn't pack PBO but I did now, and it still didn't work

**Comment by Evocation** [comment]
post your server_functions.sqf..
if u r fast enough i can do it before i go sleep

thats in 8 Mins :)

**Comment by iPopYouDrop** [comment]
https://www.mediafire.com/?3wjaa91n2yeable

**Comment by Evocation** [comment]
replace whole section and repack your server pbo:


server_checkHackers = {
	if (DZE_DYN_AntiStuck2nd > 3) then { DZE_DYN_HackerCheck = nil; DZE_DYN_AntiStuck2nd = 0; };
	if(!isNil "DZE_DYN_HackerCheck") exitWith {  DZE_DYN_AntiStuck2nd = DZE_DYN_AntiStuck2nd + 1;};
	DZE_DYN_HackerCheck = true;
	{
	if (!((isNil "_x") || {(isNull _x)})) then {
		// Epoch Admin Tools
        if(vehicle _x != _x && !(vehicle _x in PVDZE_serverObjectMonitor) && (isPlayer _x)  && !((typeOf vehicle _x) in DZE_safeVehicle) && (vehicle _x getVariable ["MalSar",0] !=1)) then {
			diag_log ("CLEANUP: KILLING A HACKER " + (name _x) + " " + str(_x) + " IN " + (typeOf vehicle _x));
			(vehicle _x) setDamage 1;
			_x setDamage 1;
			sleep 0.25;
		};
	};
		sleep 0.001;
	} count allUnits;
	DZE_DYN_HackerCheck = nil;
};

**Comment by iPopYouDrop** [comment]
Thanks, will leave reply if works

**Comment by Evocation** [comment]
yep :)

**Comment by iPopYouDrop** [comment]
Not working

**Comment by iPopYouDrop** [comment]
https://gist.github.com/iPopYouDrop/cbd22404d34d238550045012ab711060
RPT

**Comment by Evocation** [comment]
ok Oo
your mistake i found there was, that u ve gotten an semicolon behind "if (!((isNil "_x") || {(isNull _x)})) then {"

lets see your client rpt
maybe there r infos we cant see in the server one ^^

**Comment by iPopYouDrop** [comment]
Where is that located?

**Comment by Evocation** [comment]
C:\Users\<YOURACCOUNTNAME>\AppData\Local\ArmA 2 OA

**Comment by Evocation** [comment]
ArmA2OA.RPT

**Comment by iPopYouDrop** [comment]
Got it uploading now

**Comment by iPopYouDrop** [comment]
https://gist.github.com/iPopYouDrop/d0379c68c7a5f1ee63dd82e686d94d1d

**Comment by Evocation** [comment]
uhm... damn infistar...

better just copy the last 50 lines or else..

**Comment by iPopYouDrop** [comment]
https://gist.github.com/iPopYouDrop/cdb7791ac754f9836988536322d4a5e0
That good?

**Comment by Evocation** [comment]
yep, but nothing to figure out..

so whats not working exactly now? the menu doesnt show up while scroling?

**Comment by iPopYouDrop** [comment]
Yes

**Comment by Evocation** [comment]
gimme your custom fn_selfActions.sqf...

**Comment by iPopYouDrop** [comment]
I have two

**Comment by Evocation** [comment]
wat.. how this?

**Comment by Evocation** [comment]
or why?

**Comment by iPopYouDrop** [comment]
Where should it be?

**Comment by Evocation** [comment]
in your mpmissions folder
and you need to declare it in your compiles.sqf

**Comment by iPopYouDrop** [comment]
Don't see it anywhere

**Comment by iPopYouDrop** [comment]
https://gist.github.com/iPopYouDrop/1452dd4db1e39bf3e057e762714eaf4a

**Comment by Evocation** [comment]
i didnt done any with arma scripting a long time, but right now it would make some fun to help out a bit ^^

**Comment by iPopYouDrop** [comment]
Well, i deeply appreciate it!

**Comment by Evocation** [comment]
so.. i see your custom compiles.sqf is in your fixes folder in your mpmission

**Comment by Evocation** [comment]
"fixes\compiles.sqf";

**Comment by Evocation** [comment]
upload it too

**Comment by iPopYouDrop** [comment]
I don't have a fixes folder....

**Comment by Evocation** [comment]
uhm.. wat..

MPMissions -> DayZ_Epoch_11.Chernarus -> fixes -> compiles.sqf

that should be the destination, if you send me the right init ^^

**Comment by iPopYouDrop** [comment]
No fixes folder

**Comment by Evocation** [comment]
i see alot funny stuf in your init but anyways...

ive rechecked your server rtp and client rpts... there isnt any error, that would confirm this..
it have to be there or something strange is going on...

who set up your server? is it all done by u?

**Comment by iPopYouDrop** [comment]
No, I downloaded a repack from opendayz, because it already had things setup and I'm pretty lazy

**Comment by Evocation** [comment]
gimme the link
i will fast check the files...

**Comment by iPopYouDrop** [comment]
http://opendayz.net/threads/release-sheeps-epoch-repack-new-support-coming.14561/

**Comment by Evocation** [comment]
which one?

**Comment by iPopYouDrop** [comment]
Standard Overpoch i think

**Comment by Evocation** [comment]
as you can see here:

https://github.com/Fallingsheep1985/0.15_Sheeps_Back_Baby_Standard_Overpoch/tree/master/MPMissions/DayZ_Epoch_11.Chernarus

there r a fixes folder definitly... in this folder your fn_selfActions.sqf should be located...

**Comment by iPopYouDrop** [comment]
I must've not moved it somehow

**Comment by iPopYouDrop** [comment]
I'm not sure

**Comment by iPopYouDrop** [comment]
I pretty much just replaced everything

**Comment by Evocation** [comment]
if you moved it you had alot of changes in multiple files.. so i dont think you did it...

if you got already the mpmission pbo in this folder better delete it, because the game will automaticaly pack a pbo for its clients and you can work with the regular windows folder structure.... maybe you will see errors in this way that didnt apeared before ;)

**Comment by iPopYouDrop** [comment]
I'm tired and I don't really understand that last part sorry
any way to explain easier? xD

**Comment by Evocation** [comment]
uhm.. maybe my english isnt the best :)

how about teamviewer? that would be even less spam for noxsicarius :D

**Comment by iPopYouDrop** [comment]
Okay

**Comment by iPopYouDrop** [comment]
Skype or??

**Comment by Evocation** [comment]
teamviewer.com
u know it?

**Comment by iPopYouDrop** [comment]
Yea, 
you want my ID and pass?

**Comment by Evocation** [comment]
yep, would be easiest i think...

**Comment by iPopYouDrop** [comment]
156 627 099
7982

**Comment by Evocation** [comment]
all done

see u and sry noxsicarius :)

**Comment by noxsicarius** [comment]
Is the problem fixed? I don't have much time to fix everything since I'm on 7 projects at work now. I usually only have about an hour to respond to people a day. It helps when others join in.

**Comment by Evocation** [comment]
yep, its done.. not all needed files where copied and i did the remain to get it work :)
from time to time i see ppl with small problems and im glad to help with the little things ^^

**Comment by noxsicarius** [comment]
So I just realized I staged the commit for the next tool release version months ago and never pushed it out... There is a load of new features that are sitting in the test branch. I'll have to get those out this weekend. I started a nice new job where I get to play with all the newest tech toys so I've been pretty busy. Haven't seen you around on here in a while.
