### ISSUE TITLE
Safe Zone Area BUG

### ISSUE THREAD

**Issue by noxsicarius** [noxsicarius/Epoch-Admin-Tools#71]
Area only works for the player calling the script, not other players on the server

**Comment by bualdoot** [comment]
It doesn't seem to delete until restart either. I placed an area, and then deleted it a little while later, but, when I tried to place a new one, it said there was already one there. Not high priority though for me either. Just mentioning it for when ever you want to mess with it after the other stuff.

**Comment by noxsicarius** [comment]
Yes, I disabled this upon release of 1.9 because of the issues during testing. I do plan to add it back in, but I will be completely rewriting it to try and bypass whatever issue I am having. Creating a dynamic safezone is not the easiest thing it seems.

**Comment by noxsicarius** [comment]
The system should be working now. The option is in the admin menu.

To use: Select the option, select desired radius.
To remove: select the option again

Only one can be placed at a time.
